// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import yaml "gopkg.in/yaml.v3"

// NewObjectPropertiesDefault creates a new ObjectPropertiesDefault with default
// values.
func NewObjectPropertiesDefault() ObjectPropertiesDefault {
	return ObjectPropertiesDefault{
		Config: ObjectPropertiesDefaultConfig{
			Color: "#000000",
			Size:  5.0,
		},
		Count:   42.0,
		Enabled: true,
		Name:    "default_name",
		Tags: []string{
			"tag1",
			"tag2",
		},
	}
}

// NewObjectPropertiesDefaultConfig creates a new ObjectPropertiesDefaultConfig
// with default values.
func NewObjectPropertiesDefaultConfig() ObjectPropertiesDefaultConfig {
	return ObjectPropertiesDefaultConfig{
		Color: "#ffffff",
		Size:  10.0,
	}
}

type ObjectPropertiesDefault struct {
	// Config corresponds to the JSON schema field "config".
	Config ObjectPropertiesDefaultConfig `json:"config,omitempty" yaml:"config,omitempty" mapstructure:"config,omitempty"`

	// Count corresponds to the JSON schema field "count".
	Count int `json:"count,omitempty" yaml:"count,omitempty" mapstructure:"count,omitempty"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// Optional corresponds to the JSON schema field "optional".
	Optional *string `json:"optional,omitempty" yaml:"optional,omitempty" mapstructure:"optional,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags []string `json:"tags,omitempty" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`
}

type ObjectPropertiesDefaultConfig struct {
	// Color corresponds to the JSON schema field "color".
	Color string `json:"color,omitempty" yaml:"color,omitempty" mapstructure:"color,omitempty"`

	// Size corresponds to the JSON schema field "size".
	Size int `json:"size,omitempty" yaml:"size,omitempty" mapstructure:"size,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ObjectPropertiesDefaultConfig) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain ObjectPropertiesDefaultConfig
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["color"]; !ok || v == nil {
		plain.Color = "#ffffff"
	}
	if v, ok := raw["size"]; !ok || v == nil {
		plain.Size = 10.0
	}
	*j = ObjectPropertiesDefaultConfig(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *ObjectPropertiesDefaultConfig) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	type Plain ObjectPropertiesDefaultConfig
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if v, ok := raw["color"]; !ok || v == nil {
		plain.Color = "#ffffff"
	}
	if v, ok := raw["size"]; !ok || v == nil {
		plain.Size = 10.0
	}
	*j = ObjectPropertiesDefaultConfig(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ObjectPropertiesDefault) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain ObjectPropertiesDefault
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["config"]; !ok || v == nil {
		plain.Config = ObjectPropertiesDefaultConfig{
			Color: "#000000",
			Size:  5.0,
		}
	}
	if v, ok := raw["count"]; !ok || v == nil {
		plain.Count = 42.0
	}
	if v, ok := raw["enabled"]; !ok || v == nil {
		plain.Enabled = true
	}
	if v, ok := raw["name"]; !ok || v == nil {
		plain.Name = "default_name"
	}
	if v, ok := raw["tags"]; !ok || v == nil {
		plain.Tags = []string{
			"tag1",
			"tag2",
		}
	}
	*j = ObjectPropertiesDefault(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *ObjectPropertiesDefault) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	type Plain ObjectPropertiesDefault
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if v, ok := raw["config"]; !ok || v == nil {
		plain.Config = ObjectPropertiesDefaultConfig{
			Color: "#000000",
			Size:  5.0,
		}
	}
	if v, ok := raw["count"]; !ok || v == nil {
		plain.Count = 42.0
	}
	if v, ok := raw["enabled"]; !ok || v == nil {
		plain.Enabled = true
	}
	if v, ok := raw["name"]; !ok || v == nil {
		plain.Name = "default_name"
	}
	if v, ok := raw["tags"]; !ok || v == nil {
		plain.Tags = []string{
			"tag1",
			"tag2",
		}
	}
	*j = ObjectPropertiesDefault(plain)
	return nil
}
